# Generated by Django 3.2.16 on 2024-08-22 10:24

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20240729_1356'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subscribe',
            constraint=models.CheckConstraint(check=models.Q(('user', django.db.models.expressions.F('subscribing')), _negated=True), name='prevent_self_subscribe'),
        ),
    ]
